// app-shell/src/App.tsx
import './index.css';
import { Link, BrowserRouter as Router } from 'react-router-dom';
import Routers from './routes/routes';

const App: React.FC = () => {
  return (
    <div className="min-h-screen bg-gradient-to-br from-sky-100 to-purple-100 flex flex-col">
      <Router>
        <nav className="bg-white/80 shadow-lg rounded-b-2xl px-8 py-4 flex items-center justify-between mb-8 border-b border-purple-200">
          <div className="flex items-center gap-4">
            <span className="text-2xl font-extrabold text-purple-700 tracking-tight">Microfrontend Shell</span>
          </div>
          <ul className="flex gap-6 text-lg font-semibold">
            <li>
              <Link className="hover:text-purple-600 transition" to="/">Home</Link>
            </li>
            <li>
              <Link className="hover:text-blue-600 transition" to="/react">React App</Link>
            </li>
            <li>
              <Link className="hover:text-green-600 transition" to="/vue">Vue App</Link>
            </li>
          </ul>
        </nav>
        <main className="flex-1 flex flex-col items-center justify-center px-4">
          <div className="w-full max-w-3xl bg-white/90 rounded-2xl shadow-xl p-8 border border-purple-100">
            <Routers />
          </div>
        </main>
        <footer className="text-center text-xs text-gray-400 py-4 mt-8">
          Zephyr Cloud Microfrontend Demo &copy; 2025
        </footer>
      </Router>
    </div>
  );
};

export default App;

// app2-vue/src/App.vue
<script setup lang="ts">
import './index.css';
</script>

<template>
  <div class="min-h-screen bg-gradient-to-br from-green-100 to-blue-100 flex flex-col">
    <main class="flex-1 flex flex-col items-center justify-center px-4">
      <div class="w-full max-w-2xl bg-white/90 rounded-2xl shadow-xl p-8 border border-blue-100 text-center">
        <h1 class="text-4xl font-extrabold text-blue-700 mb-2">app2-vue</h1>
        <h2 class="text-xl font-semibold text-green-600 mb-4">Micro-Frontend</h2>
        <div class="mb-6">
          <span class="inline-block bg-blue-200 text-blue-800 text-xs font-bold px-3 py-1 rounded-full mr-2 mb-2">Vue 3</span>
          <span class="inline-block bg-green-200 text-green-800 text-xs font-bold px-3 py-1 rounded-full mr-2 mb-2">TypeScript</span>
          <span class="inline-block bg-yellow-200 text-yellow-800 text-xs font-bold px-3 py-1 rounded-full mr-2 mb-2">Tailwind CSS</span>
          <span class="inline-block bg-purple-200 text-purple-800 text-xs font-bold px-3 py-1 rounded-full mr-2 mb-2">Webpack 5</span>
        </div>
        <p class="text-gray-600 mb-4">This is a micro-frontend built using Vue 3, styled with Tailwind CSS, and bundled with Webpack.</p>
      </div>
    </main>
  </div>
</template>
